# Generated by Django 4.0.4 on 2022-08-26 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('profile_img', models.CharField(blank=True, max_length=500, null=True)),
                ('password', models.CharField(max_length=200)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('admin', models.BooleanField(blank=True, default=False, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
